### ISSUE TITLE
WARNING: Renegotiation needed but unimplemented

### ISSUE THREAD

**Issue by ducnmisbk** [ISBX/apprtc-ios#81]
Someone help?

I start server with apprtc-node-server.
Client 1 connect successfully
Client 2 connect to server and get below log. 

```
2017-02-16 17:38:56.449 AppRTC[3186:971716] Client connecting.
2017-02-16 17:38:56.456 AppRTC[3186:971716] Registering with room server.
2017-02-16 17:38:56.457 AppRTC[3186:971716] url = http://192.168.2.1:3000/join/678567
2017-02-16 17:38:56.818 AppRTC[3186:971716] Registered with room server.
2017-02-16 17:38:56.819 AppRTC[3186:971716] Opening WebSocket.
2017-02-16 17:38:57.451 AppRTC[3186:971716] Client connected.
2017-02-16 17:38:57.888 AppRTC[3186:972801] WARNING: Renegotiation needed but unimplemented.
2017-02-16 17:38:57.892 AppRTC[3186:971716] Failed to set session description. Error: Error Domain=RTCSDPError Code=-1 "(null)" UserInfo={error=SessionDescription is NULL.}
2017-02-16 17:38:57.892 AppRTC[3186:971716] C->RS: BYE
2017-02-16 17:38:57.893 AppRTC[3186:971716] url = http://192.168.2.1:3000/leave/678567/13001337
2017-02-16 17:38:57.916 AppRTC[3186:971716] Client disconnected.
2017-02-16 17:39:07.081 AppRTC[3186:971716] Received bad response: <!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/stylesheets/style.css"></head><body><h1>clientIds is not defined</h1><h2></h2><pre>ReferenceError: clientIds is not defined
    at Room.removeClient (/Users/.../apprtc-node-server/lib/rooms.js:55:23)
    at /Users/.../apprtc-node-server/routes/index.js:470:12
    at Rooms.get (/Users/.../apprtc-node-server/lib/rooms.js:81:5)
    at /Users/.../apprtc-node-server/routes/index.js:462:9
    at Layer.handle [as handle_request] (/Users/.../apprtc-node-server/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/.../apprtc-node-server/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/.../Project/apprtc-node-server/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/.../apprtc-node-server/node_modules/express/lib/router/layer.js:82:5)
    at /Users/.../apprtc-node-server/node_modules/express/lib/router/index.js:267:22
    at param (/Users/.../apprtc-node-server/node_modules/express/lib/router/index.js:340:14)</pre></body></html>
2017-02-16 17:39:07.087 AppRTC[3186:971716] Failed to unregister from room server.
```

**Comment by macadrich** [comment]
Check your media session.
